# Generated by Django 2.2.4 on 2019-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(choices=[(1, 'Facebook'), (2, 'Instragram'), (3, 'Linkedin'), (4, 'Celular'), (5, 'Telefone')], max_length=15)),
                ('valor_contato', models.CharField(max_length=150)),
            ],
        ),
    ]
