# Generated by Django 2.2.4 on 2019-09-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Facebook'), (2, 'Instragram'), (3, 'Linkedin'), (4, 'Celular')], max_length=15)),
                ('value', models.CharField(max_length=150)),
            ],
        ),
    ]
