# Generated by Django 2.2.4 on 2019-10-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Facebook', 'face'), ('Instagram', 'insta'), ('Linkedin', 'linke'), ('Celula', 'cel')], max_length=15),
        ),
    ]
