# Generated by Django 2.2.4 on 2019-11-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191102_1811'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsurProject',
            new_name='UserProject',
        ),
    ]
