# Generated by Django 2.2.4 on 2019-11-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_auto_20191102_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
