# Generated by Django 2.2.4 on 2019-09-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0004_delete_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('nome_endereco', models.CharField(max_length=180)),
                ('num_endereco', models.IntegerField(null=True)),
                ('estado', models.CharField(max_length=180)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=180)),
                ('complemento', models.CharField(max_length=180, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
