# Generated by Django 2.2.4 on 2019-09-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=180)),
                ('number', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=180)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=180)),
                ('complement', models.CharField(max_length=180, null=True)),
            ],
        ),
    ]
