# Generated by Django 2.2.4 on 2019-10-27 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contato', '0002_auto_20191022_2022'),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='usuario')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=90, null=True)),
                ('genre', models.CharField(blank=True, max_length=1, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('state', models.BooleanField(default=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Address')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contato.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='usuario.User')),
            ],
        ),
    ]
