# Generated by Django 2.2.4 on 2019-09-19 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contato', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=300, null=True)),
                ('photo', models.CharField(max_length=100, null=True)),
                ('birthDate', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=90, null=True)),
                ('genre', models.CharField(choices=[(1, 'Masculino'), (2, 'Feminino')], max_length=10, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('state', models.BooleanField(default=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Address')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contato.Contact')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.User')),
            ],
        ),
    ]
