# Generated by Django 2.2.4 on 2019-11-14 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(blank=True, max_length=250, primary_key=True, serialize=False)),
                ('fullName', models.CharField(blank=True, max_length=300, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='usuario')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=90, null=True)),
                ('genre', models.CharField(blank=True, max_length=1, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endereco.Address')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
