# Generated by Django 2.2.4 on 2019-09-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone2',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='availiacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_pai',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.CreateModel(
            name='UsuarioContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contato.Contato', unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('nome_endereco', models.CharField(max_length=180)),
                ('num_endereco', models.IntegerField(null=True)),
                ('estado', models.CharField(max_length=180)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=180)),
                ('complemento', models.CharField(max_length=180, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
