# Generated by Django 2.2.4 on 2019-10-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
        ('usuario', '0002_auto_20191019_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
        migrations.CreateModel(
            name='UsuarioContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contato.Contact')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.User')),
            ],
        ),
    ]
