# Generated by Django 2.2.4 on 2019-09-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190910_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
