# Generated by Django 2.2.4 on 2019-10-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
        ('usuario', '0003_auto_20191019_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioContato',
            new_name='UserContact',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='contato',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='usuario',
            new_name='user',
        ),
    ]
