# Generated by Django 2.2.4 on 2019-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_delete_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cadastro_finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
